import { ProductSeries } from './ProductSeries';
import { ArticleProduct } from './ArticleProduct';
import { Article } from './Article';
import { Order } from './Order';
import { PanoScene } from './PanoScene';
export class  Product {
  id?: number;
  articleProduct?: ArticleProduct;
  articles?: Article[];
  bad?: string;
  brand?: string;
  certificate?: string;
  code?: string;
  color?: string;
  delivery_time?: string;
  designer_comment?: string;
  discription?: string;
  e_protect?: string;
  expert_comment?: string;
  flooring_surface?: string;
  good?: string;
  install_fee?: string;
  install_type?: string;
  label_price?: number;
  name?: string;
  orders?: Order[];
  orgin_price?: number;
  panoScenes?: PanoScene[];
  standard?: string;
  state?: string;
  tags?: string;
  tone?: string;
  type?: string;
  warranty_time?: string;
  DISCRIMINATOR_PRODUCT?: string;
  materials?: string;
  numLayers?: number;
  productSeries?: ProductSeries;
  resistance?: string;
  tree?: string;
}
